<?php  //[STAMP] d4fa00bf16416d2bed2fd2911a549888
namespace Computop\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use Computop\Module\EnvironmentModule;
use Computop\Helper\Functional;
use Computop\Module\FunctionalModule;

trait FunctionalTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
