<?php  //[STAMP] 32e11c88abfa5a0d79212f3b519ac39e
namespace SprykerEcoTest\Service\Computop\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile



trait ComputopServiceTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
