<?php

/**
 * MIT License
 * Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 */

namespace SprykerEco\Shared\Computop;

interface ComputopConstants
{
    const MERCHANT_ID = 'COMPUTOP:MERCHANT_ID';
    const BLOWFISH_PASSWORD = 'COMPUTOP:BLOWFISH_PASSWORD';
    const HMAC_PASSWORD = 'COMPUTOP:HMAC_PASSWORD';

    const CREDIT_CARD_ORDER_ACTION = 'COMPUTOP:CREDIT_CARD_ORDER_ACTION';
    const AUTHORIZE_ACTION = 'COMPUTOP:AUTHORIZE_ACTION';
    const CAPTURE_ACTION = 'COMPUTOP:CAPTURE_ACTION';
    const REVERSE_ACTION = 'COMPUTOP:REVERSE_ACTION';
    const INQUIRE_ACTION = 'COMPUTOP:INQUIRE_ACTION';
    const REFUND_ACTION = 'COMPUTOP:REFUND_ACTION';

    const PAY_PAL_ORDER_ACTION = 'COMPUTOP:PAY_PAL_ORDER_ACTION';
    const DIRECT_DEBIT_ORDER_ACTION = 'COMPUTOP:DIRECT_DEBIT_ORDER_ACTION';
    const SOFORT_ORDER_ACTION = 'COMPUTOP:SOFORT_ORDER_ACTION';
    const PAYDIREKT_ORDER_ACTION = 'COMPUTOP:PAYDIREKT_ORDER_ACTION';

    const RESPONSE_MAC_REQUIRED = 'COMPUTOP:RESPONSE_MAC_REQUIRED';
    const PAYMENT_METHODS_WITHOUT_ORDER_CALL = 'COMPUTOP:PAYMENT_METHODS_WITHOUT_ORDER_CALL';
}
