name: CI

env:
    APPLICATION_ENV: 'development'
    APPLICATION_STORE: 'DE'
    PROJECT: 'Computop'

on:
    pull_request:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    ci:
        name: "Computop"
        runs-on: ubuntu-18.04
        services:
            mariadb:
                image: mariadb:10.2.1
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: false
                    MYSQL_ROOT_PASSWORD: secret
                    MYSQL_DATABASE: eu-docker
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        strategy:
            fail-fast: false
            matrix:
                php: ['7.4', '8.1']

        steps:
            - uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: mbstring, intl, bcmath
                  tools: composer:v2

            - name: Configure sysctl limits
              run: |
                  sudo swapoff -a
                  sudo sysctl -w vm.swappiness=1
                  sudo sysctl -w fs.file-max=262144
                  sudo sysctl -w vm.max_map_count=262144

            - name: Composer get cache directory
              id: composer-cache
              run: |
                  echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Composer cache
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-

            - name: Composer validate
              run: composer validate

            - name: Composer install
              run: |
                  composer --version
                  composer install

            - name: Run CodeStyle checks
              run: composer cs-check

            - name: Run codeception tests (currently not running properly)
              run: composer test

            - name: Run PHPStan
              run: composer stan

    lowest:
        name: Prefer Lowest
        runs-on: ubuntu-18.04

        steps:
            - name:  Checkout@v2
              uses: actions/checkout@v2

            - name: Validate composer.json and composer.lock
              run: composer validate

            - name: Composer get cache directory
              id: composer-cache
              run: |
                  echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Composer cache
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '7.4'
                  extensions: mbstring, intl

            - name: Composer prefer lowest
              run: composer lowest-setup

            - name: Run tests
              run: composer test

            - name: Run PHPStan (currently not running properly)
              run: composer stan || true

            - name: Validate prefer lowest
              run: vendor/bin/validate-prefer-lowest -m
